services:
  budget-board-server:
    container_name: budget-board-server
    restart: unless-stopped
    image: ghcr.io/teelur/budget-board/server:release
    build: ./server
    environment:
      Logging__LogLevel__Default: ${LOG_LEVEL:-Information}
      CLIENT_URL: ${CLIENT_URL:-budget-board-client}
      POSTGRES_HOST: ${POSTGRES_HOST:-budget-board-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE:-budgetboard}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-superSecretPassword}
      OIDC_ENABLED: ${OIDC_ENABLED:-false}
      OIDC_ISSUER: ${OIDC_ISSUER:-}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET:-}
      EMAIL_SENDER: ${EMAIL_SENDER:-}
      EMAIL_SENDER_USERNAME: ${EMAIL_SENDER_USERNAME:-}
      EMAIL_SENDER_PASSWORD: ${EMAIL_SENDER_PASSWORD:-}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST:-}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT:-587}
      DISABLE_NEW_USERS: ${DISABLE_NEW_USERS:-false}
      DISABLE_LOCAL_AUTH: ${DISABLE_LOCAL_AUTH:-false}
      AUTO_UPDATE_DB: ${AUTO_UPDATE_DB:-true}
      DISABLE_AUTO_SYNC: ${DISABLE_AUTO_SYNC:-false}
      SYNC_INTERVAL_HOURS: ${SYNC_INTERVAL_HOURS:-8}
    networks:
      - budget-board-network
    depends_on:
      budget-board-db:
        condition: service_healthy

  budget-board-client:
    container_name: budget-board-client
    restart: unless-stopped
    image: ghcr.io/teelur/budget-board/client:release
    build: ./client
    environment:
      PORT: ${PORT:-6253}
      VITE_CLIENT_URL: ${VITE_API_URL:-http://localhost:6253}
      VITE_SERVER_URL: ${VITE_SERVER_URL:-budget-board-server}
      VITE_OIDC_ENABLED: ${OIDC_ENABLED:-false}
      VITE_OIDC_PROVIDER: ${OIDC_ISSUER:-}
      VITE_OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-}
      VITE_DISABLE_NEW_USERS: ${DISABLE_NEW_USERS:-false}
      VITE_DISABLE_LOCAL_AUTH: ${DISABLE_LOCAL_AUTH:-false}
    ports:
      - ${PORT:-6253}:6253
    networks:
      - budget-board-network
    depends_on:
      - budget-board-server
  budget-board-db:
    container_name: postgres-db
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-superSecretPassword}
      POSTGRES_DB: ${POSTGRES_DATABASE:-budgetboard}
    ports:
      - "6252:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - budget-board-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d budgetboard"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:

networks:
  budget-board-network:
    name: budget-board-network
    driver: bridge
